#!/usr/bin/env python3
"""
Interview Manager Script

Manages AI interviewer sessions with automatic reconnection capabilities.
Handles cases where the AI interviewer drops from the call but candidates remain.
"""

import asyncio
import os
import sys
import signal
import time
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger

# Add current directory to path to import ai_interviewer
sys.path.insert(0, str(Path(__file__).parent))

load_dotenv(override=True)

class InterviewManager:
    def __init__(self):
        self.room_url = os.getenv("DAILY_SAMPLE_ROOM_URL")
        self.is_running = False
        self.restart_count = 0
        self.max_restarts = 5
        
    async def start_interview_session(self):
        """Start a new interview session with reconnection capability."""
        
        if not self.room_url:
            logger.error("DAILY_SAMPLE_ROOM_URL not set in .env file")
            return
            
        logger.info(f"🎬 Starting AI Interview Session")
        logger.info(f"📍 Room URL: {self.room_url}")
        logger.info(f"🤖 Backend: {os.getenv('BOT_IMPLEMENTATION', 'openai').upper()}")
        logger.info(f"👤 Tavus Avatar: {'Enabled' if os.getenv('USE_TAVUS', 'false').lower() == 'true' else 'Disabled'}")
        
        self.is_running = True
        
        while self.is_running and self.restart_count < self.max_restarts:
            try:
                logger.info(f"🚀 Starting AI Interviewer (attempt {self.restart_count + 1})")
                
                # Import and run the ai-interviewer
                from ai_interviewer import bot
                from pipecat.runner.types import RunnerArguments
                
                # Create runner arguments with fixed room
                runner_args = RunnerArguments(
                    room_url=self.room_url,
                    token=None,  # Will be generated by Daily
                )
                
                # Run the bot
                await bot(runner_args)
                
            except KeyboardInterrupt:
                logger.info("🛑 Interview session stopped by user")
                self.is_running = False
                break
                
            except Exception as e:
                self.restart_count += 1
                logger.error(f"❌ AI Interviewer crashed: {e}")
                
                if self.restart_count < self.max_restarts:
                    wait_time = min(5 * self.restart_count, 30)  # Exponential backoff
                    logger.info(f"🔄 Restarting in {wait_time} seconds...")
                    await asyncio.sleep(wait_time)
                else:
                    logger.error(f"💥 Maximum restart attempts ({self.max_restarts}) reached")
                    break
        
        logger.info("📋 Interview session ended")
    
    def stop_session(self):
        """Stop the current interview session."""
        logger.info("🛑 Stopping interview session...")
        self.is_running = False

async def main():
    """Main entry point for the interview manager."""
    
    manager = InterviewManager()
    
    # Set up signal handlers for graceful shutdown
    def signal_handler(signum, frame):
        logger.info(f"📢 Received signal {signum}")
        manager.stop_session()
    
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    
    try:
        await manager.start_interview_session()
    except Exception as e:
        logger.error(f"Fatal error in interview manager: {e}")
        sys.exit(1)

if __name__ == "__main__":
    print("🎯 AI Interview Manager")
    print("=" * 50)
    print("Features:")
    print("• Automatic reconnection if AI interviewer drops")
    print("• Persistent room URL for candidates")
    print("• Graceful error handling")
    print("• Session monitoring")
    print("=" * 50)
    
    asyncio.run(main())
